### ISSUE TITLE
problem in code

### ISSUE THREAD

**Issue by Aristot1e** [mikgroup/UFLoss#2]

**Comment by Aristot1e** [comment]
> When I ran the code ‘Step0: patch_extraction’ encountered an unsolvable problem, so I came to ask for help. This error looks like this.
> 
  0%|          | 0/676 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/img/Desktop/lff/UFLoss-main/UFloss_training/patch_extraction.py", line 88, in <module>
    im = h5py.File(folder_knee + '/' + dir_knee[0], "r")["target"][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/img/anaconda3/lib/python3.8/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'target' doesn't exist)"

> 
> I don’t know how to deal with it, so, please. Thanks for the help.

**Comment by KeWang0622** [comment]
Hi @Aristot1e, I pre-processed the data, and the "target" is the coil combined images, could you leave me your email (or send an email to kewang@berkeley.edu), I can send you the pre-processed data or the pre-processing script (depends on the copyright of fastMRI dataset).

**Comment by Aristot1e** [comment]
> Hi @Aristot1e, I pre-processed the data, and the "target" is the coil combined images, could you leave me your email (or send an email to [kewang@berkeley.edu](mailto:kewang@berkeley.edu)), I can send you the pre-processed data or the pre-processing script (depends on the copyright of fastMRI dataset).

Thank you so much, and my email is 2020110200@mail.scuec.edu. I have sent you an email asking for pre-processed data and the pre-processing script a week ago, but you haven’t replied to me. Thank you very much for your reply.

**Comment by KeWang0622** [comment]
Sure! Let me check the data copy right policy and get back to you.

**Comment by KeWang0622** [comment]
Hi, I updated our data pre-processing code at `UFloss_training/`. Let me know if you have any questions.

**Comment by Aristot1e** [comment]
OK, Thanks again. My problem has been completely solved. If there are any further questions, I will leave a message to ask or send you an email.
